[package]
name = "grafiek_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]



[dependencies]
wgpu = "0.19.3"
grafiek_engine = { path = '../../grafiek_engine' } 
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.38"
